/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './brand/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // LSG Brand Colors
        'lean-blue': 'var(--c-lean-blue)',
        'momentum-blue': 'var(--c-momentum-blue)',
        'trust-navy': 'var(--c-trust-navy)',
        'midnight-core': 'var(--c-midnight-core)',
        'soft-slate': 'var(--c-soft-slate)',
        'paper-offwhite': 'var(--c-paper-offwhite)',
        'altitude-white': 'var(--c-altitude-white)',
        'lavender-mist': 'var(--c-lavender-mist)',
        'aqua-breeze': 'var(--c-aqua-breeze)',
        'solar-orange': 'var(--c-solar-orange)',
        'sandstone': 'var(--c-sandstone)',
        // Legacy primary colors for backward compatibility
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      fontFamily: {
        sans: ['FormaDJR', 'Inter', 'system-ui', 'sans-serif'],
        forma: ['FormaDJR', 'Inter', 'system-ui', 'sans-serif'],
      },
      spacing: {
        'xs': 'var(--space-xs)',
        'sm': 'var(--space-sm)',
        'md': 'var(--space-md)',
        'lg': 'var(--space-lg)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        '4xl': 'var(--space-4xl)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
      },
      animation: {
        'lsg-reveal': 'lsg-reveal var(--duration-normal) var(--ease-out)',
        'lsg-emphasize': 'lsg-emphasize var(--duration-fast) var(--ease-in-out)',
        'lsg-volume': 'lsg-volume var(--duration-slow) var(--ease-in-out)',
        'lsg-fade-in': 'lsg-fade-in var(--duration-normal) var(--ease-out)',
        'lsg-fade-out': 'lsg-fade-out var(--duration-normal) var(--ease-out)',
        'lsg-slide-up': 'lsg-slide-up var(--duration-normal) var(--ease-out)',
        'lsg-slide-down': 'lsg-slide-down var(--duration-normal) var(--ease-out)',
        'lsg-slide-left': 'lsg-slide-left var(--duration-normal) var(--ease-out)',
        'lsg-slide-right': 'lsg-slide-right var(--duration-normal) var(--ease-out)',
        'lsg-scale-in': 'lsg-scale-in var(--duration-normal) var(--ease-out)',
        'lsg-scale-out': 'lsg-scale-out var(--duration-normal) var(--ease-out)',
        'lsg-pulse': 'lsg-pulse 2s var(--ease-in-out) infinite',
        'lsg-bounce': 'lsg-bounce 1s var(--ease-in-out)',
        'lsg-shake': 'lsg-shake 0.5s var(--ease-in-out)',
        'lsg-spin': 'lsg-spin 1s linear infinite',
      },
      transitionDuration: {
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        'ease-in': 'var(--ease-in)',
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
      },
    },
  },
  plugins: [],
}
